version: "3.7"
services:
  simple-rest-mock:
    image: simple-rest-mock:latest
    container_name: srm
    hostname: srm
    ports:
      - "8080:8080"
    environment: 
        SERVER_PORT: 8080
    volumes: 
        - .files:/opt/app/.files
